In [1]:
import torch
import tensorflow as tf

2024-10-03 13:51:16.054460: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-03 13:51:16.056927: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-03 13:51:16.065133: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-03 13:51:16.078844: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-03 13:51:16.082879: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-03 13:51:16.092995: I tensorflow/core/platform/cpu_feature_gu

In [2]:
d0 = tf.ones((1,))

2024-10-03 13:51:48.849787: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [3]:
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [8]:
d0 = torch.ones(2)


In [9]:
d0

tensor([1., 1.])

In [6]:
d1 = tf.ones((2,))

In [7]:
d1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [10]:
d0 = tf.ones((2,))

In [11]:
d0

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [12]:
d1 = tf.ones((1,2))

In [13]:
d1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

In [14]:
r =tf.ones((2,))

In [15]:
r

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>